# Generated by Django 3.1.3 on 2020-11-12 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order_creation', models.DateTimeField(auto_now_add=True)),
                ('goods', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'orders_model',
            },
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('date_birth', models.IntegerField()),
                ('date_registration', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.ordersmodel')),
            ],
            options={
                'db_table': 'users_model',
            },
        ),
    ]
