# Generated by Django 3.1.3 on 2020-11-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='date_order_creation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='date_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='date_registration',
            field=models.DateField(),
        ),
    ]
