# Generated by Django 3.1.3 on 2020-11-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_auto_20201112_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='date_order_creation',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('date_registration', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.ordersmodel')),
            ],
        ),
    ]
